### ISSUE TITLE
404 Response on Flares network

### ISSUE THREAD

**Issue by Fraganya** [saulchelewani/ussd#6]
When hitting the flares endpoint, I keep getting a 404 response.  Below are my composer.json and a sample request in postman.

<img width="1422" alt="Screenshot 2022-01-22 at 9 27 09 AM" src="https://user-images.githubusercontent.com/10554509/150630108-7fa4dd81-0c3d-4be8-abbe-c63781d09eb4.png">
<img width="698" alt="Screenshot 2022-01-22 at 9 41 35 AM" src="https://user-images.githubusercontent.com/10554509/150630116-4f289b6c-de4a-49a5-91c1-087d4857ab4f.png">

**Comment by saulchelewani** [comment]
This is resolved with the release of #7
